### ISSUE TITLE
[Feature request] add Caps lock detection

### ISSUE THREAD

**Issue by feikedonia** [pop-os/cosmic-greeter#168] opened 2024-12-27 23:06 UTC
When one has enabled the capslock, and starts typing, the password doesn't work. No surprises so far. This feature would make a small notification / warning that the Capslock is engaged, to prevent annoyances  

With Regard,

Feike

**Comment by leviport** [comment] 2024-12-27 23:12
Duplicate of https://github.com/pop-os/cosmic-greeter/issues/115

**Closed by leviport** 2024-12-27 23:12 UTC
